#!/bin/sh

#------------------------------------------------------------------------------
# in der WebUI angezeigter Gerätetyp, muss identisch sein mit dem Firmware-XML-Tag: <type name="HB-UNI-SensorX" id="HB-UNI-SensorX">
DEVICE="HB-MOIST-SENS-SW2"
# in der WebUI angezeigte Gerätebeschreibung
DEVICE_DESC="Bodenfeuchtesensor mit 2 Schaltausgaengen"
# Name der Piktogramme, bestehend aus xx.png bzw. xx_thumb.png
DEVICE_IMG=hb-moist-sens-sw2.png
DEVICE_THUMB=hb-moist-sens-sw2_thumb.png
# Name der Gerätebeschreibungs-Datei .xml
FIRMWARE_FILE=/firmware/rftypes/hb-moist-sens-sw2.xml


#------------------------------------------------------------------------------
# Edit DEVDB.tcl
devdescrFile="/www/config/devdescr/DEVDB.tcl"
devdescrSearch="array[[:space:]]*set[[:space:]]*DEV_PATHS[[:space:]]*{"

devdescrInsert="$DEVICE {{50 \/config\/img\/devices\/50\/$DEVICE_THUMB} {250 \/config\/img\/devices\/250\/$DEVICE_IMG}} "

if [ -z "`cat $devdescrFile | grep \"$DEVICE\"`" ]; then
	sed -i "s/\($devdescrSearch\)/\1$devdescrInsert/g" $devdescrFile
fi


#------------------------------------------------------------------------------
# Edit webui.js
webuiFile="/www/webui/webui.js"
webuiSearch="DEV_HIGHLIGHT[[:space:]]*=[[:space:]]*new Array();"

webuiInsert="\n"
webuiInsert="${webuiInsert}DEV_HIGHLIGHT['$DEVICE'] = new Object();\n"
webuiInsert="${webuiInsert}DEV_LIST.push('$DEVICE');\n"
webuiInsert="${webuiInsert}DEV_DESCRIPTION['$DEVICE']='$DEVICE_DESC';\n"
webuiInsert="${webuiInsert}DEV_PATHS['$DEVICE'] = new Object();\n"
webuiInsert="${webuiInsert}DEV_PATHS['$DEVICE']['50'] = '\/config\/img\/devices\/50\/$DEVICE_THUMB';\n"
webuiInsert="${webuiInsert}DEV_PATHS['$DEVICE']['250'] = '\/config\/img\/devices\/250\/$DEVICE_IMG';"

if [ -z "`cat $webuiFile | grep \"$DEVICE\"`" ]; then
	sed -i "s/\($webuiSearch\)/\1$webuiInsert/g" $webuiFile
fi

webuiSearchBegin="elvST[[:space:]]*=[[:space:]]*new Array();"

webuiInsertParam="CAP_MOIST_SENSOR|CAP_MOIST_HIGH_VALUE"
webuiInsertValue="stringTableHbCapMoistHighValue"
webuiInsert="\n"
webuiInsert="${webuiInsert}elvST['$webuiInsertParam'] = '\${$webuiInsertValue}';"
if [ -z "`cat $webuiFile | grep \"$webuiInsertParam\"`" ]; then
	sed -i "s/\($webuiSearchBegin\)/\1$webuiInsert/g" $webuiFile
fi

webuiInsertParam="CAP_MOIST_SENSOR|CAP_MOIST_LOW_VALUE"
webuiInsertValue="stringTableHbCapMoistLowValue"
webuiInsert="\n"
webuiInsert="${webuiInsert}elvST['$webuiInsertParam'] = '\${$webuiInsertValue}';"
if [ -z "`cat $webuiFile | grep \"$webuiInsertParam\"`" ]; then
	sed -i "s/\($webuiSearchBegin\)/\1$webuiInsert/g" $webuiFile
fi

webuiInsertParam="CAP_MOIST_SENSOR|ERROR=MOIST_SENSOR_OFF"
webuiInsertValue="stringTableHbCapMoistSensorFailure"
webuiInsert="\n"
webuiInsert="${webuiInsert}elvST['$webuiInsertParam'] = '\${$webuiInsertValue}';"
if [ -z "`cat $webuiFile | grep \"$webuiInsertParam\"`" ]; then
	sed -i "s/\($webuiSearchBegin\)/\1$webuiInsert/g" $webuiFile
fi


#------------------------------------------------------------------------------
### Edit stringtable_de.txt ###
stringtable_deFile="/www/config/stringtable_de.txt"

stringtable_deInsert="CAP_MOIST_SENSOR|CAP_MOIST_HIGH_VALUE\t\${stringTableHbCapMoistHighValue}"
if [ -z "`cat $stringtable_deFile | grep \"CAP_MOIST_SENSOR|CAP_MOIST_HIGH_VALUE"`" ]; then
    echo -e $stringtable_deInsert >> $stringtable_deFile
fi
stringtable_deInsert="CAP_MOIST_SENSOR|CAP_MOIST_LOW_VALUE\t\${stringTableHbCapMoistLowValue}"
if [ -z "`cat $stringtable_deFile | grep \"CAP_MOIST_SENSOR|CAP_MOIST_LOW_VALUE"`" ]; then
    echo -e $stringtable_deInsert >> $stringtable_deFile
fi
stringtable_deInsert="CAP_MOIST_SENSOR|ERROR=MOIST_SENSOR_OFF\t\${stringTableHbCapMoistSensorFailure}"
if [ -z "`cat $stringtable_deFile | grep \"CAP_MOIST_SENSOR|ERROR=MOIST_SENSOR_OFF"`" ]; then
    echo -e $stringtable_deInsert >> $stringtable_deFile
fi


#------------------------------------------------------------------------------
### Edit translate.lang.stringtable.js ###
translate_deFile="/www/webui/js/lang/de/translate.lang.stringtable.js"
translate_deSearch="\"dummy\" : \"\","

translate_deInsert="\n    \"stringTableHbCapMoistHighValue\" : \"HIGH Value (Trocken [bei 0%25 Feuchte])\","
if [ -z "`cat $translate_deFile | grep \"stringTableHbCapMoistHighValue\"`" ]; then
	sed -i "s/\($translate_deSearch\)/\1$translate_deInsert/g" $translate_deFile
fi
translate_deInsert="\n    \"stringTableHbCapMoistLowValue\" : \"LOW Value (Nass [bei 100%25 Feuchte])\","
if [ -z "`cat $translate_deFile | grep \"stringTableHbCapMoistLowValue\"`" ]; then
	sed -i "s/\($translate_deSearch\)/\1$translate_deInsert/g" $translate_deFile
fi
translate_deInsert="\n    \"stringTableHbCapMoistSensorFailure\" : \"Fehler Bodenfeuchtesensor<br\/>(Sensor ist deaktiviert)\","
if [ -z "`cat $translate_deFile | grep \"stringTableHbCapMoistSensorFailure\"`" ]; then
	sed -i "s/\($translate_deSearch\)/\1$translate_deInsert/g" $translate_deFile
fi